### Get all contacts
GET http://localhost:3000/contacts
Content-Type: application/json

###

### Get single contact by ID
GET http://localhost:3000/contacts/682d122a6cad2929d3330d82
Content-Type: application/json

###

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "okoye nonsoemmanuel",
  "lastName": "Smith",
  "email": "eliase@example.com",
  "favoriteColor": "purple",
  "birthdate": "1995-04-10"
}

###

### Update a contact
PUT http://localhost:3000/contacts/68273ab49c3ac9efc0a51582
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "favoriteColor": "red",
  "birthdate": "1995-04-10"
}

###

### Delete a contact
DELETE http://localhost:3000/contacts/68273ab49c3ac9efc0a51582
  
  {"firstName": "Okoye",
  "lastName": "Emmanuel",
  "email": "amazingwoman@test.com",
  "favoriteColor": "Green",
  "birthday": "12/12/20"
  }